"""
Project Euler Problem 45
========================

Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle     T[n]=n(n+1)/2   1, 3, 6, 10, 15, ...
Pentagonal   P[n]=n(3n-1)/2  1, 5, 12, 22, 35, ...
Hexagonal    H[n]=n(2n-1)    1, 6, 15, 28, 45, ...

It can be verified that T[285] = P[165] = H[143] = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

from utils import is_triangular, is_pentagonal, hexagonal_values_generator

for hexagonal_val in hexagonal_values_generator():
    if is_triangular(hexagonal_val) and is_pentagonal(hexagonal_val):
        if hexagonal_val not in (1, 40755):
            print(hexagonal_val)
            break
